name: Compilation & tests

on: [push, pull_request]

jobs:
  job_build:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make TESTING=1

      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: passwords-app
          path: bin

  job_test:
    name: Test
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: passwords-app
          path: bin

      - name: Run test
        run: |
          pip install -r tests/requirements.txt
          pytest

      - name: Upload Speculos log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: speculos-log
          path: speculos.log

